server:
  port: 8080
spring:
#  datasource:
#    url: jdbc:mysql://database-1.coluq7bvskjj.ap-northeast-2.rds.amazonaws.com:3306/mainproject?serverTimezone=Asia/Seoul
#    username: admin
#    password: 12341234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#    defer-datasource-initialization: true